# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Firestore', '~> 5.3.0'
pod 'Firebase/Auth', '~> 5.3.0'

target 'tinythoughts' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tinythoughts
  target 'tinythoughtsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tinythoughts-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tinythoughts-tvOS

  target 'tinythoughts-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
